---
title: "BayesianFinal5"
output: pdf_document
date: "2022-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
#a)

epl = read.csv("epl.csv",header = T)
z = epl %>% arrange(HomeTeam)
names = unique(z$HomeTeam)

played = matrix(0,20,20)
for (i in 1:146) {
  played[epl[i,2],epl[i,5]] = 1
}

for (i in 1:20) {played[i,i] = 1}

#b)
home_points = matrix(0,20,20)
away_points = matrix(0,20,20)
for (i in 1:146) {
  if(epl[i,3]>epl[i,6]){
    home_points[epl[i,2],epl[i,5]] = 3
  }
  else if(epl[i,3]<epl[i,6]){
    away_points[epl[i,2],epl[i,5]] = 3
  }
  else {
    home_points[epl[i,2],epl[i,5]] = 1
    away_points[epl[i,2],epl[i,5]] = 1
  }
  
}

#c)
tPoints = matrix(0,1,20)
for (i in 1:20) {
  tPoints[i] = sum(home_points[i,])+sum(away_points[,i])
}

source("Final5.R",knitr::knit_global())

#h)
lPoints = cbind.data.frame(names,colMeans(sampleMatrix5[,423:442]))
colnames(lPoints) = c("names","Points")
lPoints = lPoints %>% arrange(Points)
#Top 4
lPoints[17:20,]
#Bottom 3
lPoints[1:3,]

#i)
lRank = cbind.data.frame(names,colMeans(sampleMatrix5[,1:20]))
colnames(lRank) = c("names","Rank")
lRank = lRank %>% arrange(Rank)
#Top 4
lRank[1:4,]
#Bottom 3
lRank[18:20,]

#j)
lRanks = cbind.data.frame(names,colMeans(sampleMatrix5[,21:40]))
colnames(lRanks) = c("names","Rank1")
lRanks = lRanks %>% arrange(Rank1)
#Most Often
lRanks[20,]

#k
topRanks = matrix(sampleMatrix5[,21:100],nrow = nrow(sampleMatrix5),ncol = 80)
top4 = vector(mode = "double",length = 20)
for(i in 1:20){
  top4[i] = (sum(topRanks[,i]) + sum(topRanks[,i+20]) + sum(topRanks[,i+40]) + sum(topRanks[,i+60]))/nrow(topRanks)
}

top4 = cbind.data.frame(names,top4)
top4 = top4 %>% arrange(-top4)
top4[1:4,]

#l)
botRanks = matrix(sampleMatrix5[,361:420],nrow = nrow(sampleMatrix5),ncol = 60)
bot3 = vector(mode = "double",length = 20)
for(i in 1:20){
  bot3[i] = (sum(botRanks[,i]) + sum(botRanks[,i+20]) + sum(botRanks[,i+40]))/nrow(botRanks)
}

bot3 = cbind.data.frame(names,bot3)
bot3 = bot3 %>% arrange(-bot3)
bot3[1:3,]

#m)
uWin =0
cWin = 0
draw = 0

for (i in 1:nrow(sampleMatrix5)) {
  if(sampleMatrix5[i,421]==3){
    cWin = cWin + 1
  }
  else if (sampleMatrix5[i,421]==0){
    uWin = uWin + 1
  }
  
  else{
    draw = draw + 1
  }
}

uWin/nrow(sampleMatrix5)
cWin/nrow(sampleMatrix5)
draw/nrow(sampleMatrix5)


```

